🎏 Flag to identify model cannot be load by hf even if hf_config is not None
microsoft/Olive pull request #533
Opened 2023-09-01 09:07 UTC by trajepl

## Describe your changes

For torch model, if hf_config is not None, the loader will fall into huggingface model loader even if the model is local pytorch model(e.g, the output of TensorRTConversion).

Then we add a flag to identify model cannot be load by hf even if hf_config is not None. This flag is set by pass specifically. 

## Checklist before requesting a review
- [ ] Add unit tests for this change.
- [ ] Make sure all tests can pass.
- [ ] Update documents if necessary.
- [ ] Format your code by running `pre-commit run --all-files`
- [ ] Is this a user-facing change? If yes, give a description of this change to be included in the release notes.

## (Optional) Issue link

2023-09-01 11:20 UTC, guotuofeng commented on olive/model/__init__.py
> +        is_complete_hf_folder: bool = True,
>is_complete_hf_folder [](http://example.com/codeflow?start=8&length=21)

could we use hf_config for this case by making it be Union[bool, Dict, HFConfig]?

2023-09-01 11:22 UTC, guotuofeng commented on olive/model/__init__.py
> +        is_complete_hf_folder: bool = True,
@jambayk

2023-09-01 11:22 UTC, guotuofeng requested changes
let's wait comments from @jambayk

2023-09-01 20:16 UTC, devang-ml reviewed
If a model is no longer a complete HF model then what's the use of hf_config ? Should the TorchTRTConversion pass set the hf_config to None ?

2023-09-04 00:36 UTC, guotuofeng commented
> If a model is no longer a complete HF model then what's the use of hf_config ? Should the TorchTRTConversion pass set the hf_config to None ?

@devang-ml, the reason for assigning hf_config to not None value is because transformer optimization pass would like to use original model config like num_heads/hidden_size for the converted onnx model if it is coming from HF model.

@trajepl / @jambayk 
There are several approach for current scenario:
1. save the TorchTRTConversion output as PYTORCH_TORCH_SCRIPT and when loading model choose torch.jit.load if the format is torch script and ignore the hf_config. In this way, we still use hf_config to contains the model config, which seems still not perfect since the hf_config is used for two scenarios. 1), load the pytorch model, 2), provide the model config. It seems go against https://en.wikipedia.org/wiki/Single-responsibility_principle.
2. Another solution is add a dedicated model_config in OliveModel so all kinds of model could leverage it in future. The responsibility boundary is clear: it is only for providing the model configuration regardless whether it is for model loading or other purpose.

Please let me know your feedbacks

2023-09-04 00:56 UTC, guotuofeng commented
@jambayk / @xiaoyu-work , 

What's the reason that adding hf_config in ONNX model in PR https://github.com/microsoft/Olive/pull/258?

2023-09-04 02:40 UTC, trajepl commented
> 2\. dedicated

Prefer option #2. For separated model config, I would like to complete it automatically if the model is from huggingface. More like the hf_config.config is previous discussion. 
And the separated method can keep the logic clearer.

2023-09-05 08:38 UTC, closed without merging